# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 22:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('avatar_url', models.URLField(blank=True, default=b'')),
                ('city', models.CharField(blank=True, max_length=200)),
                ('bio', models.TextField(blank=True, default=b'', max_length=500)),
                ('skills', models.TextField(blank=True, default=b'', max_length=500)),
                ('mission', models.CharField(blank=True, max_length=250)),
                ('personal_website_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True, default=b'http://twitter.com/')),
                ('facebook_url', models.URLField(blank=True, default=b'http://facebook.com/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
