# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 23:00
from __future__ import unicode_literals

import Profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=Profiles.models.get_user_path),
        ),
    ]
