# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 22:59
from __future__ import unicode_literals

import Activities.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, default=b'', null=True)),
                ('activity_type', models.CharField(choices=[(b'TOU', b'Tourism/Territory'), (b'CLA', b'Classes/Workshop'), (b'EVN', b'Event/Party')], max_length=3)),
                ('time', models.DateTimeField(default=datetime.datetime(2017, 5, 23, 0, 59, 28, 728989))),
                ('photo', models.ImageField(blank=True, null=True, upload_to=Activities.models.get_activity_path)),
                ('attendees_limit', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0.0)),
                ('attendees', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default=b'', max_length=500)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2017, 5, 22, 0, 59, 28, 730606))),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_activity', to='Activities.Activity')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_location', to='Activities.Location'),
        ),
        migrations.AddField(
            model_name='activity',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_author', to=settings.AUTH_USER_MODEL),
        ),
    ]
