# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 22:59
from __future__ import unicode_literals

import Accommodations.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(default=b'', max_length=500)),
                ('room_size', models.CharField(choices=[(b'FPD', b'4 persons dorm'), (b'DOU', b'Double'), (b'SNG', b'Single')], max_length=3)),
                ('room_type', models.CharField(choices=[(b'LCL', b'Monthly'), (b'GST', b'Nightly'), (b'ALL', b'Monthly and Nightly')], max_length=3)),
                ('main_photo', models.ImageField(blank=True, null=True, upload_to=Accommodations.models.get_accommodations_path)),
                ('external_booking_url', models.URLField(blank=True, null=True)),
                ('price_per_day', models.FloatField(default=0.0)),
                ('price_per_month', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='AccommodationPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=b'', max_length=140)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=Accommodations.models.get_accommodation_photos_path)),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_accommodation', to='Accommodations.Accommodation')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_date', models.DateField(default=datetime.datetime(2017, 5, 23, 0, 59, 28, 734197))),
                ('checkout_date', models.DateField(default=datetime.datetime(2017, 5, 24, 0, 59, 28, 734229))),
                ('status', models.CharField(choices=[(b'ACC', b'Accepted'), (b'WFA', b'Waiting for approval'), (b'WFP', b'Waiting for payment'), (b'DEC', b'Declined')], default=b'WFA', max_length=3)),
                ('price', models.FloatField(default=0.0)),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_of_accommodation', to='Accommodations.Accommodation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_tenant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
